# torchtitan Config.toml
[job]
dump_folder = "outputs"
description = "Llama 3 31B 1-bit kmeans QAT training"
custom_config_module = "llama3_qat.experiment.config"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "llama3_qat"
flavor = "31B"
# test folder with tokenizer.json, for debug purpose only
tokenizer_path = "./debug_assets/tokenizer"
converters = ["quantized_linear"]

[optimizer]
name = "AdamW"
lr = 0.01
eps = 1e-8
weight_decay = 0.1

[lr_scheduler]
warmup_steps = 0  
decay_ratio = 0.1  
decay_type = "linear"

[training]
dataset = "test_dataset"  
local_batch_size = 1
global_batch_size = 2
seq_len = 2048
max_norm = 1.0  
steps = 10 

[compile]
enable = false

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
interval = 5
export_dtype = "float32"
async_mode = "disabled"

[activation_checkpoint]
mode = "none"  
selective_ac_option = '2'  

[quantization]
quantizer = "nonlinear"
target_bit_width = 1
qat_start_step = 1000
relative_scale = "absmean"
